// database.js
// Este arquivo age como seu Banco de Dados. 
// Para adicionar novos itens, basta copiar a estrutura e colar abaixo.

const LDX_DATABASE = [
  // ==========================================
  // SÉRIES POPULARES
  // ==========================================
  { id: 1, title: "Stranger Things", type: "series", year: 2022, rating: "8.7", duration: "4 Temp.", desc: "Quando um garoto desaparece, uma pequena cidade descobre um mistério envolvendo experimentos secretos e forças sobrenaturais.", genres: ["Sci-Fi", "Drama"], img: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb3IPfG8dHiARG3RV.jpg", bg: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg", top10: true, videoUrl: "b9EkMc79ZSU" },
  { id: 2, title: "The Last of Us", type: "series", year: 2023, rating: "8.8", duration: "1 Temp.", desc: "Após uma pandemia global, um sobrevivente é contratado para contrabandear uma menina de 14 anos.", genres: ["Drama", "Ação"], img: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg", bg: "https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg", top10: true, videoUrl: "uLtkt8BonwM" },
  { id: 3, title: "House of the Dragon", type: "series", year: 2022, rating: "8.5", duration: "1 Temp.", desc: "A história da Casa Targaryen, 200 anos antes dos eventos de Game of Thrones.", genres: ["Fantasia"], img: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg", bg: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg", top10: true, videoUrl: "DotnY7P2Q_c" },
  { id: 4, title: "Wednesday", type: "series", year: 2022, rating: "8.1", duration: "1 Temp.", desc: "Wednesday Addams investiga assassinatos na Escola Nevermore.", genres: ["Comédia", "Mistério"], img: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg", bg: "https://image.tmdb.org/t/p/original/iHSwvRVsRyxpXgFEYgQHwsdlT9o.jpg", videoUrl: "Di3WS1CgEjc" },
  { id: 5, title: "The Witcher", type: "series", year: 2023, rating: "8.2", duration: "3 Temp.", desc: "Geralt de Rívia, um caçador de monstros, luta para encontrar seu lugar num mundo cruel.", genres: ["Fantasia"], img: "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg", bg: "https://image.tmdb.org/t/p/original/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg", videoUrl: "ndl1W4ncMWs" },
  { id: 6, title: "Breaking Bad", type: "series", year: 2008, rating: "9.5", duration: "5 Temp.", desc: "Um professor de química com câncer fabrica metanfetamina.", genres: ["Crime", "Drama"], img: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", bg: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg", top10: true, videoUrl: "HhesaQXLuRY" },
  { id: 7, title: "Peaky Blinders", type: "series", year: 2013, rating: "8.8", duration: "6 Temp.", desc: "Uma gangue familiar na Inglaterra de 1919.", genres: ["Crime"], img: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg", bg: "https://image.tmdb.org/t/p/original/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg", videoUrl: "oVzVdvGIC7U" },
  { id: 8, title: "Dark", type: "series", year: 2017, rating: "8.7", duration: "3 Temp.", desc: "O desaparecimento de crianças revela um mistério de viagem no tempo.", genres: ["Mistério", "Sci-Fi"], img: "https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg", bg: "https://image.tmdb.org/t/p/original/75GFqrnPfJaeSJlpvJHVcmwLNNU.jpg", videoUrl: "rrwycJ08PSA" },
  { id: 9, title: "Money Heist", type: "series", year: 2017, rating: "8.2", duration: "5 Partes", desc: "O Professor recruta um grupo para assaltar a Casa da Moeda Real.", genres: ["Ação", "Crime"], img: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg", bg: "https://image.tmdb.org/t/p/original/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg", videoUrl: "htgQqn2Uaw8" },
  { id: 10, title: "Squid Game", type: "series", year: 2021, rating: "8.0", duration: "1 Temp.", desc: "Jogadores falidos competem em jogos infantis por um prêmio tentador.", genres: ["Ação", "Drama"], img: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg", bg: "https://image.tmdb.org/t/p/original/qw3J9cNeLioOLoR68WX7z79aCdK.jpg", videoUrl: "oqxAJKy0II4" },
  { id: 11, title: "Game of Thrones", type: "series", year: 2011, rating: "9.2", duration: "8 Temp.", desc: "Nove famílias nobres lutam pelo controle das terras míticas de Westeros.", genres: ["Fantasia", "Drama"], img: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg", bg: "https://image.tmdb.org/t/p/original/suopoADq0k8YZr4dQXcU6pToj6s.jpg", top10: true, videoUrl: "KPLWWIOCOOQ" },
  { id: 12, title: "The Office", type: "series", year: 2005, rating: "9.0", duration: "9 Temp.", desc: "Um documentário sobre o cotidiano de funcionários de escritório.", genres: ["Comédia"], img: "https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg", bg: "https://image.tmdb.org/t/p/original/1rYfIitGPJ0RwT4fCv1UvS4qQ6u.jpg", videoUrl: "LHOtME2DL4g" },
  { id: 13, title: "Friends", type: "series", year: 1994, rating: "8.9", duration: "10 Temp.", desc: "Seis amigos moram em Manhattan e passam por aventuras amorosas e profissionais.", genres: ["Comédia", "Romance"], img: "https://image.tmdb.org/t/p/w500/f496cm9enuEsZkSPzCwnTESEK5s.jpg", bg: "https://image.tmdb.org/t/p/original/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg", videoUrl: "hDNNmeeJs1Q" },
  { id: 14, title: "The Big Bang Theory", type: "series", year: 2007, rating: "7.9", duration: "12 Temp.", desc: "Um grupo de nerds enfrenta a vida e o amor.", genres: ["Comédia"], img: "https://image.tmdb.org/t/p/w500/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg", bg: "https://image.tmdb.org/t/p/original/nGsNruW3W27V6r4gkyc3iiEGsKR.jpg", videoUrl: "WBb3fo1g-Q0" },
  { id: 15, title: "Loki", type: "series", year: 2021, rating: "8.2", duration: "2 Temp.", desc: "O vilão Loki assume o papel de herói em uma nova realidade temporal.", genres: ["Ação", "Fantasia"], img: "https://image.tmdb.org/t/p/w500/voHUmluYmKyleFkTu3lOXQG702u.jpg", bg: "https://image.tmdb.org/t/p/original/q3jHCb4dMfYF6ojikKuHd6LscxC.jpg", videoUrl: "nW948VaY10Y" },
  { id: 16, title: "The Mandalorian", type: "series", year: 2019, rating: "8.7", duration: "3 Temp.", desc: "Um caçador de recompensas solitário em uma galáxia muito, muito distante.", genres: ["Sci-Fi", "Ação"], img: "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg", bg: "https://image.tmdb.org/t/p/original/9ijMGlJKqcslswWUzTEwScm82Gs.jpg", videoUrl: "aOC8E8z_ifw" },
  { id: 17, title: "Better Call Saul", type: "series", year: 2015, rating: "9.0", duration: "6 Temp.", desc: "A história de transformação de Jimmy McGill no advogado Saul Goodman.", genres: ["Crime", "Drama"], img: "https://image.tmdb.org/t/p/w500/fC2Jm2Zu3fmJKq3p14igL4vplan.jpg", bg: "https://image.tmdb.org/t/p/original/84DYZGi6w6W9Bv9ic0s9ScWFPSH.jpg", videoUrl: "HN4oyyBH5xE" },
  { id: 18, title: "Chernobyl", type: "series", year: 2019, rating: "9.4", duration: "Minissérie", desc: "O desastre nuclear de Chernobyl em 1986.", genres: ["Drama", "História"], img: "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg", bg: "https://image.tmdb.org/t/p/original/43Dv6d4cYkdBRMa4yF5JKV7wrpo.jpg", videoUrl: "m9G2LPqtx0I" },
  { id: 19, title: "The Crown", type: "series", year: 2016, rating: "8.6", duration: "6 Temp.", desc: "A história da Rainha Elizabeth II.", genres: ["Drama", "Biografia"], img: "https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg", bg: "https://image.tmdb.org/t/p/original/5fz4bjGzwcZoR4UkJY2fVCFQTPa.jpg", videoUrl: "JWtnJjn6ng0" },
  { id: 20, title: "Ozark", type: "series", year: 2017, rating: "8.5", duration: "4 Temp.", desc: "Uma família se muda para os Ozarks para lavar dinheiro.", genres: ["Crime", "Drama"], img: "https://image.tmdb.org/t/p/w500/pCGyPVrI9Fzw6XkGDkMZeLHBqLp.jpg", bg: "https://image.tmdb.org/t/p/original/y3tABLMH3Ie7pNvdFRFSNwP0ue1.jpg", videoUrl: "5hAXFilhV6g" },

  // ==========================================
  // FILMES DE AÇÃO E BLOCKBUSTERS
  // ==========================================
  { id: 101, title: "Oppenheimer", type: "movie", year: 2023, rating: "8.9", duration: "3h", desc: "A história do físico J. Robert Oppenheimer e a bomba atômica.", genres: ["Drama", "Biografia"], img: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", bg: "https://image.tmdb.org/t/p/original/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg", top10: true, videoUrl: "uYPbbksJxIg" },
  { id: 102, title: "Barbie", type: "movie", year: 2023, rating: "7.0", duration: "1h 54m", desc: "Barbie e Ken no mundo perfeito de Barbie Land.", genres: ["Comédia", "Fantasia"], img: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg", bg: "https://image.tmdb.org/t/p/original/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg", top10: true, videoUrl: "pBk4NYhWNMM" },
  { id: 103, title: "Interstellar", type: "movie", year: 2014, rating: "8.7", duration: "2h 49m", desc: "Exploradores viajam por um buraco de minhoca para salvar a humanidade.", genres: ["Sci-Fi", "Aventura"], img: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", bg: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg", top10: true, videoUrl: "zSWdZVtXT7E" },
  { id: 104, title: "Top Gun: Maverick", type: "movie", year: 2022, rating: "8.3", duration: "2h 11m", desc: "Maverick treina pilotos para uma missão impossível.", genres: ["Ação", "Drama"], img: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg", bg: "https://image.tmdb.org/t/p/original/AaV1YIdWKhw9f0fJhAiGJOh1xzT.jpg", videoUrl: "giXco2jaZ_4" },
  { id: 105, title: "The Batman", type: "movie", year: 2022, rating: "7.8", duration: "2h 56m", desc: "Batman investiga corrupção em Gotham.", genres: ["Ação", "Crime"], img: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fvber9r3Jo7QnB77r.jpg", bg: "https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg", videoUrl: "mqqft2x_Aa4" },
  { id: 106, title: "Avatar: O Caminho da Água", type: "movie", year: 2022, rating: "7.8", duration: "3h 12m", desc: "Jake Sully enfrenta uma nova ameaça em Pandora.", genres: ["Ação", "Sci-Fi"], img: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg", bg: "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg", videoUrl: "d9MyW72ELq0" },
  { id: 107, title: "John Wick 4", type: "movie", year: 2023, rating: "7.8", duration: "2h 49m", desc: "John Wick enfrenta a Alta Mesa.", genres: ["Ação", "Crime"], img: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg", bg: "https://image.tmdb.org/t/p/original/7I6VUdPj6tQECNHdviJkUHD2u89.jpg", videoUrl: "qEVUtrkdg_B4" },
  { id: 108, title: "Duna", type: "movie", year: 2021, rating: "8.0", duration: "2h 35m", desc: "Paul Atreides viaja para o planeta mais perigoso.", genres: ["Sci-Fi", "Aventura"], img: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg", bg: "https://image.tmdb.org/t/p/original/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg", videoUrl: "n9xhJrPXop4" },
  { id: 109, title: "Vingadores: Ultimato", type: "movie", year: 2019, rating: "8.4", duration: "3h 1m", desc: "Os heróis fazem um último esforço contra Thanos.", genres: ["Ação", "Heróis"], img: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg", bg: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg", top10: true, videoUrl: "TcMBFSGVi1c" },
  { id: 110, title: "Coringa", type: "movie", year: 2019, rating: "8.4", duration: "2h 2m", desc: "Arthur Fleck descende à loucura.", genres: ["Crime", "Drama"], img: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", bg: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YMDNqKDs.jpg", videoUrl: "zAGVQLHvwYH4" },
  { id: 111, title: "Homem-Aranha: Sem Volta Para Casa", type: "movie", year: 2021, rating: "8.3", duration: "2h 28m", desc: "Peter Parker pede ajuda ao Doutor Estranho.", genres: ["Ação", "Heróis"], img: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg", bg: "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg", videoUrl: "JfVOs4VSpmA" },
  { id: 112, title: "Titanic", type: "movie", year: 1997, rating: "7.9", duration: "3h 14m", desc: "Um romance a bordo do trágico navio Titanic.", genres: ["Drama", "Romance"], img: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYj.jpg", bg: "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg", videoUrl: "kVrqfYjkTdQ" },
  { id: 113, title: "O Senhor dos Anéis: O Retorno do Rei", type: "movie", year: 2003, rating: "9.0", duration: "3h 21m", desc: "A batalha final pela Terra-média.", genres: ["Aventura", "Fantasia"], img: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg", bg: "https://image.tmdb.org/t/p/original/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg", videoUrl: "r5X-hFf6Bwo" },
  { id: 114, title: "Jurassic Park", type: "movie", year: 1993, rating: "8.2", duration: "2h 7m", desc: "Um parque de dinossauros sai de controle.", genres: ["Aventura", "Sci-Fi"], img: "https://image.tmdb.org/t/p/w500/xbA5kfsRqT3wUBjt28PR3L7QaG.jpg", bg: "https://image.tmdb.org/t/p/original/ah3GuJlb4Ew8i6UaFnI1n1bqdC6.jpg", videoUrl: "lc0UehY3JiE" },
  { id: 115, title: "Matrix", type: "movie", year: 1999, rating: "8.7", duration: "2h 16m", desc: "A realidade é uma simulação.", genres: ["Sci-Fi", "Ação"], img: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", bg: "https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg", videoUrl: "vKQi3bBA1y8" },
  { id: 116, title: "Clube da Luta", type: "movie", year: 1999, rating: "8.8", duration: "2h 19m", desc: "Um homem insone forma um clube de luta underground.", genres: ["Drama"], img: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg", bg: "https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg", videoUrl: "SUXWAEX2jlg" },
  { id: 117, title: "A Origem", type: "movie", year: 2010, rating: "8.8", duration: "2h 28m", desc: "Roubo de segredos através dos sonhos.", genres: ["Sci-Fi", "Ação"], img: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Ber.jpg", bg: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg", videoUrl: "YoHD9XEInc0" },
  { id: 118, title: "Parasita", type: "movie", year: 2019, rating: "8.5", duration: "2h 12m", desc: "Uma família se infiltra em uma casa rica.", genres: ["Thriller", "Drama"], img: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", bg: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg", videoUrl: "5xH0HfJnQeE" },
  { id: 119, title: "Gladiador", type: "movie", year: 2000, rating: "8.5", duration: "2h 35m", desc: "Um general romano se torna gladiador.", genres: ["Ação", "Drama"], img: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg", bg: "https://image.tmdb.org/t/p/original/xGrTmM5PpjEaxB8umyrPIJJkHtn.jpg", videoUrl: "owK1qIcmd-4" },
  { id: 120, title: "O Poderoso Chefão", type: "movie", year: 1972, rating: "9.2", duration: "2h 55m", desc: "O patriarca de uma família do crime transfere o controle.", genres: ["Crime", "Drama"], img: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg", bg: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg", videoUrl: "sY1S34973zA" },
  { id: 121, title: "Pulp Fiction", type: "movie", year: 1994, rating: "8.9", duration: "2h 34m", desc: "As vidas de assassinos e gângsteres se entrelaçam.", genres: ["Crime"], img: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", bg: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg", videoUrl: "tGpTpVyI_OQ" },
  { id: 122, title: "Forrest Gump", type: "movie", year: 1994, rating: "8.8", duration: "2h 22m", desc: "Um homem com QI baixo presencia momentos históricos.", genres: ["Drama", "Romance"], img: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg", bg: "https://image.tmdb.org/t/p/original/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg", videoUrl: "bLvqoHBGjzE" },
  { id: 123, title: "De Volta para o Futuro", type: "movie", year: 1985, rating: "8.5", duration: "1h 56m", desc: "Marty McFly viaja de 1985 para 1955.", genres: ["Aventura", "Comédia"], img: "https://image.tmdb.org/t/p/w500/7lyBcpYBdQtR3OtGuufk9D6I01i.jpg", bg: "https://image.tmdb.org/t/p/original/4V5GrkCwqnPwD8qCXxL6KQfncgO.jpg", videoUrl: "qYgjtPWi9QU" },
  { id: 124, title: "O Exorcista", type: "movie", year: 1973, rating: "7.7", duration: "2h 2m", desc: "Uma mãe procura ajuda para sua filha possuída.", genres: ["Terror"], img: "https://image.tmdb.org/t/p/w500/4ucLcVHf7MYtoIPlKwEILnLJRU8.jpg", bg: "https://image.tmdb.org/t/p/original/nBH4LM7nSiZzL4slRYF5m5lHLz.jpg", videoUrl: "0iCx5X0VQ_U" },
  { id: 125, title: "Psicose", type: "movie", year: 1960, rating: "8.5", duration: "1h 49m", desc: "Uma secretária foge com dinheiro e fica em um motel sinistro.", genres: ["Terror", "Thriller"], img: "https://image.tmdb.org/t/p/w500/ww6Jj3Y9L9hADrRJh1MuM2lD8KW.jpg", bg: "https://image.tmdb.org/t/p/original/dzE9C3t1D4Q3lHHD65CbvwZJSig.jpg", videoUrl: "WzZImLkV5Vc" },
  { id: 126, title: "O Iluminado", type: "movie", year: 1980, rating: "8.4", duration: "2h 26m", desc: "Um escritor enlouquece em um hotel isolado.", genres: ["Terror"], img: "https://image.tmdb.org/t/p/w500/9fgh3Ms2QvScf6Q3G5b0hW1YPFC.jpg", bg: "https://image.tmdb.org/t/p/original/pB9G3MQsi9BaPdF89Rf3L6WnK7b.jpg", videoUrl: "S014c8Ofv6U" },
  
  // ==========================================
  // ANIMAÇÕES
  // ==========================================
  { id: 201, title: "Homem-Aranha: Através do Aranhaverso", type: "movie", year: 2023, rating: "8.9", duration: "2h 20m", desc: "Miles Morales viaja pelo multiverso.", genres: ["Animação", "Ação"], img: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", bg: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg", videoUrl: "shW9i6NKJPo" },
  { id: 202, title: "Super Mario Bros. O Filme", type: "movie", year: 2023, rating: "7.1", duration: "1h 32m", desc: "Mario e Luigi salvam a Princesa Peach.", genres: ["Animação", "Família"], img: "https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ber.jpg", bg: "https://image.tmdb.org/t/p/original/9lBVu4GKuiG0RvGtPpfPiiKo88u.jpg", videoUrl: "TnGl01FkMMo" },
  { id: 203, title: "Soul", type: "movie", year: 2020, rating: "8.0", duration: "1h 40m", desc: "Um músico viaja para fora de seu corpo.", genres: ["Animação", "Fantasia"], img: "https://image.tmdb.org/t/p/w500/hYqOjJ7Gh0fbqZe1dJb7fYsJm0b.jpg", bg: "https://image.tmdb.org/t/p/original/1QNTsmlu7zuWjqzYQ1C35NjdiKY.jpg", videoUrl: "xOsLIiY2pwI" },
  { id: 204, title: "Toy Story", type: "movie", year: 1995, rating: "8.3", duration: "1h 21m", desc: "Brinquedos ganham vida quando ninguém está olhando.", genres: ["Animação", "Família"], img: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg", bg: "https://image.tmdb.org/t/p/original/nowHgvW43Fdf98YsrSaxh97oWL.jpg", videoUrl: "KYz2jr0xiuo" },
  { id: 205, title: "Procurando Nemo", type: "movie", year: 2003, rating: "8.2", duration: "1h 40m", desc: "Um peixe-palhaço tenta encontrar seu filho.", genres: ["Animação"], img: "https://image.tmdb.org/t/p/w500/syPWyeeqzTwIxQwKbDfTWmJmCN0.jpg", bg: "https://image.tmdb.org/t/p/original/nHq61Npkxa9nKkR1bsP3p7L63CY.jpg", videoUrl: "wZdpNswQd-c" },
  
  // ==========================================
  // TERROR
  // ==========================================
  { id: 301, title: "Invocação do Mal", type: "movie", year: 2013, rating: "7.5", duration: "1h 52m", desc: "Investigadores paranormais trabalham em um caso aterrorizante.", genres: ["Terror"], img: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg", bg: "https://image.tmdb.org/t/p/original/ng6SSB3JdLMjRqnDjo4VFTX9jQ6.jpg", videoUrl: "k10ETZ41P5o" },
  { id: 302, title: "IT: A Coisa", type: "movie", year: 2017, rating: "7.3", duration: "2h 15m", desc: "Sete crianças enfrentam um palhaço aterrorizante.", genres: ["Terror", "Fantasia"], img: "https://image.tmdb.org/t/p/w500/9E2y5Q7WlCVNEhP5GiVTXneI3wz.jpg", bg: "https://image.tmdb.org/t/p/original/tTlAA0REGPXSZPf4c5oZL0Ta0RX.jpg", videoUrl: "FnCdOQsX5kc" },
  { id: 303, title: "Hereditário", type: "movie", year: 2018, rating: "7.3", duration: "2h 7m", desc: "Uma família descobre segredos aterrorizantes após a morte da avó.", genres: ["Terror", "Drama"], img: "https://image.tmdb.org/t/p/w500/2K2senEMgdwB7id6b4Nkph1U8vK.jpg", bg: "https://image.tmdb.org/t/p/original/njiQmvbBlVsLctV3wnB6TNz1emK.jpg", videoUrl: "V6wWcWlZpuI" }
];
